package PO;
// Generated 23-apr-2016 1.33.43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * Biglietti generated by hbm2java
 */

@Entity
@Table(name="BIGLIETTI")
public class Biglietto  implements java.io.Serializable {

     @Id
     @GeneratedValue
     private String codice;
     private BigDecimal tariffa;
     @Temporal(javax.persistence.TemporalType.DATE)
     private Date dataDiValidita;
     @ManyToOne
     @JoinColumn(name = "TitoloEsposizione")
     private Esposizione titoloEsposizione;
     @ManyToOne
     @JoinColumn(name = "idVisitatore")
     private Utente idVisitatore;
     @ManyToOne
     @JoinColumn(name = "CodiceCategoria")
     private Categoria codiceCategoria;
     
    @ManyToMany(mappedBy="biglietti")
    private Set<Servizioaggiuntivo>serviziagg;

    public Biglietto() {
    }

	
    public Biglietto(String codice, BigDecimal tariffa, Utente idVisitatore) {
        this.codice = codice;
        this.tariffa = tariffa;
        this.idVisitatore = idVisitatore;
    }
    
    public Biglietto(String codice, BigDecimal tariffa,Utente idVisitatore, Categoria codiceCategoria) {
       this.codice = codice;
       this.tariffa = tariffa;
       this.idVisitatore = idVisitatore;
       this.codiceCategoria = codiceCategoria;
    }
    
    public Biglietto(String codice, BigDecimal tariffa, Date dataDiValidita, Esposizione titoloEsposizione, Utente idVisitatore) {
       this.codice = codice;
       this.tariffa = tariffa;
       this.dataDiValidita = dataDiValidita;
       this.titoloEsposizione = titoloEsposizione;
       this.idVisitatore = idVisitatore;
    }
    
    public Biglietto(String codice, BigDecimal tariffa, Date dataDiValidita, Esposizione titoloEsposizione, Utente idVisitatore, Categoria codiceCategoria) {
       this.codice = codice;
       this.tariffa = tariffa;
       this.dataDiValidita = dataDiValidita;
       this.titoloEsposizione = titoloEsposizione;
       this.idVisitatore = idVisitatore;
       this.codiceCategoria = codiceCategoria;
    }

    public Biglietto(String codice, BigDecimal tariffa, Date dataDiValidita, Esposizione titoloEsposizione, Utente idVisitatore, Categoria codiceCategoria, Set<Servizioaggiuntivo> serviziagg) {
        this.codice = codice;
        this.tariffa = tariffa;
        this.dataDiValidita = dataDiValidita;
        this.titoloEsposizione = titoloEsposizione;
        this.idVisitatore = idVisitatore;
        this.codiceCategoria = codiceCategoria;
        this.serviziagg = serviziagg;
    }
    
   
    public String getCodice() {
        return this.codice;
    }
    
    public void setCodice(String codice) {
        this.codice = codice;
    }
    public BigDecimal getTariffa() {
        return this.tariffa;
    }
    
    public void setTariffa(BigDecimal tariffa) {
        this.tariffa = tariffa;
    }
    public Date getDataDiValidita() {
        return this.dataDiValidita;
    }
    
    public void setDataDiValidita(Date dataDiValidita) {
        this.dataDiValidita = dataDiValidita;
    }
    public Esposizione getTitoloEsposizione() {
        return this.titoloEsposizione;
    }
    
    public void setTitoloEsposizione(Esposizione titoloEsposizione) {
        this.titoloEsposizione = titoloEsposizione;
    }
    public Utente getIdVisitatore() {
        return this.idVisitatore;
    }
    
    public void setIdVisitatore(Utente idVisitatore) {
        this.idVisitatore = idVisitatore;
    }
    public Categoria getCodiceCategoria() {
        return this.codiceCategoria;
    }
    
    public void setCodiceCategoria(Categoria codiceCategoria) {
        this.codiceCategoria = codiceCategoria;
    }

    public Set<Servizioaggiuntivo> getServiziagg() {
        return serviziagg;
    }

    public void setServiziagg(Set<Servizioaggiuntivo> serviziagg) {
        this.serviziagg = serviziagg;
    }
    
    




}


