package PO;
// Generated 23-apr-2016 1.33.43 by Hibernate Tools 4.3.1

import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "CATEGORIE")
public class Categoria implements java.io.Serializable {

    @Id
    @GeneratedValue
    private String codice;
    private String descrizione;
    private String documento;
    private float sconto;

    @OneToMany(mappedBy = "codiceCategoria")
    private Set<Biglietto> biglietti;

    public Categoria() {
    }

    public Categoria(String codice, String descrizione, String documento, float sconto) {
        this.codice = codice;
        this.descrizione = descrizione;
        this.documento = documento;
        this.sconto = sconto;
    }

    public Categoria(String codice, String descrizione, String documento, float sconto, Set<Biglietto> biglietti) {
        this.codice = codice;
        this.descrizione = descrizione;
        this.documento = documento;
        this.sconto = sconto;
        this.biglietti = biglietti;
    }

    public String getCodice() {
        return this.codice;
    }

    public void setCodice(String codice) {
        this.codice = codice;
    }

    public String getDescrizione() {
        return this.descrizione;
    }

    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    public String getDocumento() {
        return this.documento;
    }

    public void setDocumento(String documento) {
        this.documento = documento;
    }

    public float getSconto() {
        return this.sconto;
    }

    public void setSconto(float sconto) {
        this.sconto = sconto;
    }

    public Set<Biglietto> getBiglietti() {
        return biglietti;
    }

    public void setBiglietti(Set<Biglietto> biglietti) {
        this.biglietti = biglietti;
    }

}
