package PO;
// Generated 23-apr-2016 1.33.43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Serviziaggiuntivi generated by hbm2java
 */
@Entity
@Table(name="SERVIZIAGGIUNTIVI")
public class Servizioaggiuntivo  implements java.io.Serializable {

     @Id
     @GeneratedValue
     private String codice;
     private String descrizione;
     private BigDecimal prezzo;
     
     @ManyToMany
     @JoinTable(
     name="APPARTENERE",
     joinColumns={@JoinColumn(name="CodiceServizioAggiuntivo")},
     inverseJoinColumns={@JoinColumn(name="CodiceBiglietto")}
    )
     private Set<Biglietto> biglietti;

    public Servizioaggiuntivo() {
    }

	
    public Servizioaggiuntivo(String codice, BigDecimal prezzo) {
        this.codice = codice;
        this.prezzo = prezzo;
    }
    public Servizioaggiuntivo(String codice, String descrizione, BigDecimal prezzo) {
       this.codice = codice;
       this.descrizione = descrizione;
       this.prezzo = prezzo;
    }
    public Servizioaggiuntivo(String codice, String descrizione, BigDecimal prezzo, Set<Biglietto> biglietti) {
        this.codice = codice;
        this.descrizione = descrizione;
        this.prezzo = prezzo;
        this.biglietti = biglietti;
    }
    
   
    public String getCodice() {
        return this.codice;
    }
    
    public void setCodice(String codice) {
        this.codice = codice;
    }
    public String getDescrizione() {
        return this.descrizione;
    }
    
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }
    public BigDecimal getPrezzo() {
        return this.prezzo;
    }
    
    public void setPrezzo(BigDecimal prezzo) {
        this.prezzo = prezzo;
    }

    public Set<Biglietto> getBiglietti() {
        return biglietti;
    }

    public void setBiglietti(Set<Biglietto> biglietti) {
        this.biglietti = biglietti;
    }


}


